# Generated by Django 5.1.12 on 2025-11-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='file_name',
        ),
    ]
