apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcript-meeting-recorder-api
  labels:
    app: transcript-meeting-recorder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcript-meeting-recorder-api
  template:
    metadata:
      labels:
        app: transcript-meeting-recorder-api
    spec:
      initContainers:
      - name: migrations
        image: vanyabrucker/transcript # base image name from skaffold.yaml
        command: [ "python", "manage.py", "migrate" ]
        envFrom:
        - configMapRef:
            name: transcript-meeting-recorder-config
        - secretRef:
            name: transcript-secrets
      containers:
      - name: api
        image: vanyabrucker/transcript # base image name from skaffold.yaml
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: transcript-meeting-recorder-config
        - secretRef:
            name: transcript-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2.5Gi" # 2Gi for the bot + 0.5Gi for the API server
            cpu: "1500m"   # 1000m for the bot + 500m for the API server