# Allow the default service account to create and manage pods in the default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bot-pod-creator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bot-pod-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: bot-pod-creator
  apiGroup: rbac.authorization.k8s.io