apiVersion: v1
kind: Service
metadata:
  name: transcript-meeting-recorder-api
  labels:
    app: transcript-meeting-recorder-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: transcript-meeting-recorder-api
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}